import type { Lang } from "@/lib/types";

export function resolveLang(raw?: string): Lang {
  return raw === "en" ? "en" : "es";
}

export const landingCopy = {
  es: {
    navModel: "Modelo",
    navFlow: "Cómo funciona",
    navPlatform: "Plataforma",
    navPhase: "Explorar ContratoLimpio",
    heroEyebrow: "SECOP II · IA cívica para leer contratación pública",
    heroTitleA: "Lee la",
    heroTitleB: "contratación",
    heroTitleC: "con contexto",
    heroBody:
      "VeedurIA convierte millones de contratos en una lectura guiada. Ordena primero lo que más se sale del patrón, explica las señales del modelo y te devuelve siempre a la fuente oficial, sin perderte en el ruido.",
    heroPrimary: "Explorar ContratoLimpio",
    heroSecondary: "Cómo funciona",
    heroProtocolA: "El modelo ordena primero las rupturas del patrón.",
    heroProtocolB: "Cada caso traduce la anomalía en señales legibles.",
    heroProtocolC: "La revisión siempre termina en el expediente oficial.",
    heroDataLabel: "Dato visible",
    heroPlay: "Campo interactivo",
    heroPlayBody:
      "Mueve el cursor o el dedo para alterar la red de señales. La interfaz responde como una superficie viva, no como un dashboard muerto.",
    heroLegendFocus: "foco",
    heroLegendModel: "modelo",
    heroLegendAlert: "alerta",
    heroCardSourceLabel: "fuente",
    heroCardSourceTitle: "SECOP II",
    heroCardSourceBody: "Contratos oficiales, filtros abiertos y retorno directo al expediente público.",
    heroCardModelLabel: "modelo",
    heroCardModelTitle: "Isolation Forest",
    heroCardModelBody: "La capa ML ordena la superficie contractual y eleva primero las rupturas del patrón.",
    heroCardReviewLabel: "lectura",
    heroCardReviewTitle: "Ruta de revisión",
    heroCardReviewBody: "El producto conecta señal, explicación y verificación en una sola secuencia visual.",
    heroGraphLabel: "tráfico de señales",
    stats: [
      ["2.8M", "contratos procesados", "Base histórica suficiente para que el modelo no dependa de intuiciones aisladas."],
      ["25", "variables por contrato", "Monto, plazo, competencia, proveedor, temporalidad y concentración."],
      ["5%", "franja priorizada", "La porción más inusual es la primera capa de revisión, no una condena."],
      ["3", "fases de producto", "ContratoLimpio hoy, PromesMetro y SigueElDinero como expansión natural."],
    ],
    modelEyebrow: "Modelo",
    modelTitle: "IA explicable para vigilar, no para adivinar",
    modelBody:
      "La plataforma no pretende reemplazar criterio humano. Ordena el universo contractual, muestra por qué un caso sube de prioridad y obliga a volver al expediente oficial.",
    modelCards: [
      ["IF", "Isolation Forest", "Aprende cómo luce un contrato típico y encuentra desviaciones sin depender de etiquetas previas."],
      ["25", "Variables legibles", "El modelo usa señales que se pueden explicar: monto, oferentes, modalidad, temporalidad y concentración."],
      ["0-100", "Puntaje interpretable", "Un número alto significa contrato inusual frente al patrón observado. No significa culpa."],
      ["REV", "Revisión humana", "La IA prioriza. Periodistas, ciudadanos y organizaciones revisan el contexto y la documentación."],
    ],
    flowEyebrow: "Flujo",
    flowTitle: "Del ruido contractual a una pista que sí se entiende",
    flowBody:
      "La experiencia está pensada para leer rápido: mapa, casos para empezar, explicación y verificación. No para perderse en tablas interminables.",
    flowCards: [
      ["ML", "Detectar", "ContratoLimpio sube primero los contratos que más rompen el comportamiento habitual."],
      ["SH", "Explicar", "Cada caso muestra qué factores empujaron el puntaje y qué parte del patrón se quebró."],
      ["SC", "Verificar", "Todo termina en SECOP II. La plataforma acompaña la lectura; no reemplaza la evidencia."],
    ],
    platformEyebrow: "Plataforma",
    platformTitle: "Tres fases, una sola arquitectura cívica",
    platformBody:
      "Fase 1 ya está viva. Las siguientes fases conectan promesas, dinero, redes y contratistas para convertir VeedurIA en una superficie completa de escrutinio público.",
    phases: [
      ["Activa", "ContratoLimpio", "Semáforo de riesgo sobre SECOP II con mapa, casos guiados, factores explicables y vínculo oficial."],
      ["En diseño", "PromesMetro", "Promesas públicas frente a acción política real, con evidencia, coherencia y trazabilidad."],
      ["En diseño", "SigueElDinero", "Redes entre donantes, contratistas, funcionarios y sanciones para detectar patrones de captura."],
    ],
    ctaTitle: "Empieza por lo que hoy ya se puede auditar",
    ctaBody:
      "La nueva capa de producto ya no depende de Streamlit para la experiencia. ContratoLimpio vive como módulo web y queda listo para escalar al resto de VeedurIA.",
    ctaButton: "Abrir ContratoLimpio",
    footer: "VeedurIA · plataforma cívica bilingüe para leer contratación pública con evidencia y contexto",
    languageLabel: "Idioma",
    statVisualCoverage: "Cobertura visible",
    statVisualSignals: "Capas leídas",
    statVisualThreshold: "Umbrales de lectura",
    statVisualRoadmap: "Ruta del producto",
  },
  en: {
    navModel: "Model",
    navFlow: "How it works",
    navPlatform: "Platform",
    navPhase: "Explore ContratoLimpio",
    heroEyebrow: "SECOP II · Civic AI for reading public procurement",
    heroTitleA: "Read public",
    heroTitleB: "procurement",
    heroTitleC: "with context",
    heroBody:
      "VeedurIA turns millions of contracts into a guided reading surface. It brings forward the strongest pattern breaks, explains the model signals, and always returns you to the official source without getting lost in the noise.",
    heroPrimary: "Explore ContratoLimpio",
    heroSecondary: "How it works",
    heroProtocolA: "The model brings pattern breaks to the front first.",
    heroProtocolB: "Each case translates anomaly into readable signals.",
    heroProtocolC: "Review always ends at the official record.",
    heroDataLabel: "Visible data",
    heroPlay: "Interactive field",
    heroPlayBody:
      "Move the cursor or your finger to disturb the signal mesh. The interface reacts like a living surface instead of a dead dashboard.",
    heroLegendFocus: "focus",
    heroLegendModel: "model",
    heroLegendAlert: "alert",
    heroCardSourceLabel: "source",
    heroCardSourceTitle: "SECOP II",
    heroCardSourceBody: "Official contracts, open filters, and a direct path back to the public file.",
    heroCardModelLabel: "model",
    heroCardModelTitle: "Isolation Forest",
    heroCardModelBody: "The ML layer orders the contract surface and pushes pattern breaks to the front.",
    heroCardReviewLabel: "review",
    heroCardReviewTitle: "Reading path",
    heroCardReviewBody: "The product links signal, explanation, and verification in one visual flow.",
    heroGraphLabel: "signal traffic",
    stats: [
      ["2.8M", "contracts processed", "Enough historical base for the model to avoid relying on isolated hunches."],
      ["25", "variables per contract", "Value, timing, competition, provider, electoral timing, and concentration."],
      ["5%", "priority band", "The most unusual slice is reviewed first, not treated as a verdict."],
      ["3", "product phases", "ContratoLimpio today, PromesMetro and SigueElDinero as the next expansion."],
    ],
    modelEyebrow: "Model",
    modelTitle: "Explainable AI built for scrutiny, not guesswork",
    modelBody:
      "The platform does not replace human judgment. It orders the contract universe, shows why a case rises in priority, and forces the reader back to the official record.",
    modelCards: [
      ["IF", "Isolation Forest", "Learns what a typical contract looks like and finds deviations without relying on labeled cases."],
      ["25", "Readable variables", "The model uses explainable signals: amount, bidders, modality, timing, and concentration."],
      ["0-100", "Interpretable score", "A high number means the contract looks unusual against the observed pattern. It does not mean guilt."],
      ["REV", "Human review", "AI prioritizes. Journalists, citizens, and watchdogs review context and documentation."],
    ],
    flowEyebrow: "Flow",
    flowTitle: "From raw procurement noise to a lead you can actually read",
    flowBody:
      "The experience is built for fast reading: map, lead cases, explanation, and verification. Not for getting lost inside endless tables.",
    flowCards: [
      ["ML", "Detect", "ContratoLimpio pushes the strongest deviations from normal behavior to the top first."],
      ["SH", "Explain", "Each case shows which factors raised the score and what part of the pattern broke."],
      ["SC", "Verify", "Everything ends in SECOP II. The platform supports the reading; it does not replace evidence."],
    ],
    platformEyebrow: "Platform",
    platformTitle: "Three phases, one civic architecture",
    platformBody:
      "Phase 1 is already live. The next phases connect promises, money, networks, and contractors so VeedurIA becomes a complete accountability surface.",
    phases: [
      ["Active", "ContratoLimpio", "Risk signal over SECOP II with map, guided cases, explainable factors, and the official source link."],
      ["In design", "PromesMetro", "Public promises against real political action, with evidence, coherence, and traceability."],
      ["In design", "SigueElDinero", "Networks across donors, contractors, public officials, and sanctions to spot capture patterns."],
    ],
    ctaTitle: "Start with what can already be audited today",
    ctaBody:
      "The new product layer no longer depends on Streamlit for the experience. ContratoLimpio now lives as a web module, ready to scale across the rest of VeedurIA.",
    ctaButton: "Open ContratoLimpio",
    footer: "VeedurIA · bilingual civic platform for reading public procurement with evidence and context",
    languageLabel: "Language",
    statVisualCoverage: "Visible coverage",
    statVisualSignals: "Readable layers",
    statVisualThreshold: "Reading thresholds",
    statVisualRoadmap: "Product path",
  },
} as const;

export const contractsCopy = {
  es: {
    navPhase1: "ContratoLimpio",
    navPhase2: "PromesMetro",
    navPhase3: "SigueElDinero",
    stateActive: "Activa",
    stateSoon: "En diseño",
    pageEyebrow: "Fase 1 · SECOP II",
    pageTitle: "Empieza por la señal, no por la tabla",
    pageBody:
      "El módulo principal te lleva primero a la lectura útil: territorio, señal, explicación y verificación. La tabla queda al fondo, como respaldo, no como experiencia principal.",
    simpleFilters: "Definir corte",
    applyFilters: "Aplicar corte",
    searchPlaceholder: "Buscar entidad o proveedor",
    searchLabel: "Búsqueda",
    filterDepartment: "Departamento",
    filterRisk: "Riesgo",
    filterModality: "Modalidad",
    filterAll: "Todo",
    riskAll: "Todo",
    riskHigh: "Alto",
    riskMedium: "Medio",
    riskLow: "Bajo",
    togglePreview: "Vista rápida",
    toggleFull: "Historial completo",
    metricSlice: "Corte activo",
    metricAlerts: "Alertas altas",
    metricTerritory: "Territorio líder",
    metricModel: "Dato más reciente",
    dashboardTitle: "Lectura del corte",
    dashboardBody: "Estos indicadores cambian con cada territorio, búsqueda o nivel de riesgo que selecciones.",
    guideTitle: "Cómo leer este corte",
    guideBody: "Territorio, señal, explicación y fuente oficial, en ese orden.",
    guideStepTerritory: "Define territorio, riesgo o búsqueda.",
    guideStepSignal: "Abre el caso líder para entender la señal.",
    guideStepVerify: "Verifica en SECOP II antes de concluir.",
    modelHonesty: "El modelo prioriza contratos inusuales. No prueba irregularidad.",
    kpiContracts: "Contratos en corte",
    kpiPriorityValue: "Valor priorizado",
    kpiSelectedCase: "Caso enfocado",
    kpiSelectedSignal: "Señal principal",
    currentSlice: "Lectura actual",
    currentSliceDefault: "Todo Colombia",
    mapTitle: "Mapa de riesgo por departamento",
    mapBody: "Haz clic en un territorio para reordenar los casos sugeridos y reducir ruido.",
    mapLegendLow: "menor señal",
    mapLegendHigh: "mayor señal",
    mapFocusTitle: "Territorio dominante del corte",
    mapFocusBody: "Esta base resume qué territorio concentra hoy la lectura y te deja saltar a cortes rápidos sin perder contexto.",
    mapQuickCuts: "Cortes rápidos",
    mapFreshness: "Fecha más reciente",
    casesTitle: "Empieza por aquí",
    casesBody: "Estos casos resumen mejor el corte actual: señal fuerte, monto relevante y recencia.",
    casesGuide: "Abre un caso para ver por qué subió y cómo verificarlo.",
    focusTitle: "Caso que mejor resume el corte",
    focusBody: "Aquí ves primero el contrato que mejor combina señal, monto y recencia dentro del corte activo.",
    otherCasesTitle: "Otros casos útiles del corte",
    otherCasesBody: "Sirven para contrastar el patrón actual sin bajar todavía a toda la tabla.",
    noCases: "No hay contratos para este corte.",
    whyHere: "Por qué está aquí",
    selectedCase: "Caso seleccionado",
    factorsTitle: "Factores que elevaron el puntaje",
    factorsHint: "Las barras más largas representan señales que más empujaron el caso fuera del patrón esperado.",
    detailEntity: "Entidad",
    detailProvider: "Proveedor",
    detailModality: "Modalidad",
    detailValue: "Valor",
    methodology: "Metodología",
    methodologyBody:
      "Isolation Forest prioriza contratos estadísticamente inusuales. SHAP traduce esa anomalía en factores legibles. El resultado sirve para orientar revisión, no para concluir ilegalidad.",
    summaryEntities: "Entidades que conviene revisar primero",
    summaryModalities: "Modalidades con riesgo medio más alto",
    summaryContracts: "contratos",
    summaryMax: "máx.",
    summaryMean: "prom.",
    analysisTitle: "Sala de análisis",
    analysisBody: "Cambia entre resúmenes, explorador y metodología sin bajar por toda la página.",
    analysisEntities: "Entidades",
    analysisModalities: "Modalidades",
    analysisExplorer: "Explorador",
    analysisMethodology: "Modelo",
    tableTitle: "Contratos del corte actual",
    tableBody: "Sirve para contrastar, ordenar y validar lo que el mapa y los casos ya te señalaron.",
    tableNote: "Aquí ves el universo completo del corte seleccionado. Arriba está la lectura guiada; abajo, la evidencia completa.",
    tableScore: "Puntaje",
    tableEntity: "Entidad",
    tableDepartment: "Departamento",
    tableModality: "Modalidad",
    tableValue: "Valor",
    tableSource: "Fuente",
    tableValueRelative: "Peso en el corte",
    verify: "Ver en SECOP II",
    ethicalNote: "Alerta preventiva. No es una acusación automática.",
    rows: "filas",
    loading: "Cargando",
    previous: "Anterior",
    next: "Siguiente",
  },
  en: {
    navPhase1: "ContratoLimpio",
    navPhase2: "PromesMetro",
    navPhase3: "SigueElDinero",
    stateActive: "Active",
    stateSoon: "In design",
    pageEyebrow: "Phase 1 · SECOP II",
    pageTitle: "Start with the signal, not the table",
    pageBody:
      "The main module takes you first to the useful reading: territory, signal, explanation, and verification. The table stays below as support, not as the primary experience.",
    simpleFilters: "Define slice",
    applyFilters: "Apply slice",
    searchPlaceholder: "Search entity or provider",
    searchLabel: "Search",
    filterDepartment: "Department",
    filterRisk: "Risk",
    filterModality: "Modality",
    filterAll: "All",
    riskAll: "All",
    riskHigh: "High",
    riskMedium: "Medium",
    riskLow: "Low",
    togglePreview: "Quick view",
    toggleFull: "Full history",
    metricSlice: "Active slice",
    metricAlerts: "High alerts",
    metricTerritory: "Leading territory",
    metricModel: "Latest data point",
    dashboardTitle: "Slice reading",
    dashboardBody: "These indicators change with every territory, search, or risk level you select.",
    guideTitle: "How to read this slice",
    guideBody: "Territory, signal, explanation, and official source, in that order.",
    guideStepTerritory: "Define territory, risk, or search.",
    guideStepSignal: "Open the lead case to understand the signal.",
    guideStepVerify: "Verify in SECOP II before concluding.",
    modelHonesty: "The model prioritizes unusual contracts. It does not prove wrongdoing.",
    kpiContracts: "Contracts in slice",
    kpiPriorityValue: "Prioritized value",
    kpiSelectedCase: "Focused case",
    kpiSelectedSignal: "Primary signal",
    currentSlice: "Current reading",
    currentSliceDefault: "All Colombia",
    mapTitle: "Risk map by department",
    mapBody: "Click a territory to reorder the lead cases and reduce noise.",
    mapLegendLow: "lower signal",
    mapLegendHigh: "higher signal",
    mapFocusTitle: "Leading territory in this slice",
    mapFocusBody: "This base shows which territory is dominating the reading right now and lets you jump across quick slices without losing context.",
    mapQuickCuts: "Quick slices",
    mapFreshness: "Latest date",
    casesTitle: "Start here",
    casesBody: "These cases best summarize the current slice: strong signal, relevant value, and recency.",
    casesGuide: "Open a case to see why it rose and how to verify it.",
    focusTitle: "Case that best summarizes the slice",
    focusBody: "This is the first contract to inspect because it best combines signal, value, and recency in the active slice.",
    otherCasesTitle: "Other useful cases in this slice",
    otherCasesBody: "Use them to contrast the current pattern before dropping into the full table.",
    noCases: "No contracts in this slice.",
    whyHere: "Why it is here",
    selectedCase: "Selected case",
    factorsTitle: "Factors that raised the score",
    factorsHint: "Longer bars represent signals that pushed the case furthest outside the expected pattern.",
    detailEntity: "Entity",
    detailProvider: "Provider",
    detailModality: "Modality",
    detailValue: "Value",
    methodology: "Methodology",
    methodologyBody:
      "Isolation Forest prioritizes statistically unusual contracts. SHAP turns that anomaly into readable factors. The result guides review; it does not establish wrongdoing.",
    summaryEntities: "Entities worth checking first",
    summaryModalities: "Modalities with the highest mean risk",
    summaryContracts: "contracts",
    summaryMax: "max",
    summaryMean: "mean",
    analysisTitle: "Analysis room",
    analysisBody: "Switch between summaries, explorer, and methodology without scrolling through the whole page.",
    analysisEntities: "Entities",
    analysisModalities: "Modalities",
    analysisExplorer: "Explorer",
    analysisMethodology: "Model",
    tableTitle: "Contracts in the current slice",
    tableBody: "Use it to contrast, sort, and validate what the map and the lead cases already surfaced.",
    tableNote: "This is the full universe for the selected slice. The guided reading sits above; the complete evidence lives here.",
    tableScore: "Score",
    tableEntity: "Entity",
    tableDepartment: "Department",
    tableModality: "Modality",
    tableValue: "Value",
    tableSource: "Source",
    tableValueRelative: "Weight in slice",
    verify: "Open in SECOP II",
    ethicalNote: "Preventive alert. This is not an automatic accusation.",
    rows: "rows",
    loading: "Loading",
    previous: "Previous",
    next: "Next",
  },
} as const;
