import type { Lang } from "@/lib/types";

export function resolveLang(raw?: string): Lang {
  return raw === "en" ? "en" : "es";
}

export const landingCopy = {
  es: {
    navModel: "Modelo",
    navFlow: "Cómo funciona",
    navPlatform: "Plataforma",
    navPhase: "Entrar a la plataforma",
    heroEyebrow: "SECOP II · Promesas · Redes · IA civica para escrutinio publico",
    heroTitleA: "Contratos, promesas",
    heroTitleB: "y redes",
    heroTitleC: "en una sola lectura",
    heroBody:
      "VeedurIA ya vive como una sola app web. ContratoLimpio detecta señales atipicas en SECOP II, VotóMeter contrasta votos nominales con perfil programático visible, y SigueElDinero prepara la capa de redes para seguir el rastro completo.",
    heroPrimary: "Abrir ContratoLimpio",
    heroSecondary: "Abrir VotóMeter",
    heroProtocolA: "ContratoLimpio ordena primero lo que rompe el patron contractual.",
    heroProtocolB: "VotóMeter contrasta voto nominal, gaceta y coherencia programática.",
    heroProtocolC: "SigueElDinero sumara redes, flujos y concentracion politica.",
    heroDataLabel: "Dato visible",
    heroPlay: "Superficie de plataforma",
    heroPlayBody:
      "Toca un departamento para mover el foco territorial y ver cómo cambian la lectura principal, las rutas activas y la capa de datos disponible.",
    heroMapCaption: "Toca el mapa para cambiar el foco territorial de la plataforma.",
    heroLegendFocus: "foco",
    heroLegendModel: "modelo",
    heroLegendAlert: "alerta",
    heroCardSourceLabel: "fuente",
    heroCardSourceTitle: "ContratoLimpio",
    heroCardSourceBody: "Contratos oficiales, filtros abiertos y retorno directo al expediente publico.",
    heroCardModelLabel: "modelo",
    heroCardModelTitle: "VotóMeter",
    heroCardModelBody: "Voto nominal, perfil programático y gaceta quedan en una sola lectura para periodistas, ONG y ciudadanía.",
    heroCardReviewLabel: "lectura",
    heroCardReviewTitle: "SigueElDinero",
    heroCardReviewBody: "La tercera fase conectara donantes, contratistas y funcionarios dentro del mismo shell web.",
    heroGraphLabel: "tráfico de señales",
    stats: [
      ["2.8M", "contratos procesados", "Base histórica suficiente para que el modelo no dependa de intuiciones aisladas."],
      ["25", "variables por contrato", "Monto, plazo, competencia, proveedor, temporalidad y concentración."],
      ["5%", "franja priorizada", "La porción más inusual es la primera capa de revisión, no una condena."],
      ["3", "fases activas o en despliegue", "ContratoLimpio y VotóMeter ya viven en web; SigueElDinero entra como la siguiente capa."],
    ],
    modelEyebrow: "Modelo",
    modelTitle: "IA explicable para vigilar, no para adivinar",
    modelBody:
      "La plataforma no pretende reemplazar criterio humano. Ordena el universo contractual, muestra por qué un caso sube de prioridad y obliga a volver al expediente oficial.",
    modelCards: [
      ["IF", "Isolation Forest", "Aprende cómo luce un contrato típico y encuentra desviaciones sin depender de etiquetas previas."],
      ["25", "Variables legibles", "El modelo usa señales que se pueden explicar: monto, oferentes, modalidad, temporalidad y concentración."],
      ["0-100", "Puntaje interpretable", "Un número alto significa contrato inusual frente al patrón observado. No significa culpa."],
      ["REV", "Revisión humana", "La IA prioriza. Periodistas, ciudadanos y organizaciones revisan el contexto y la documentación."],
    ],
    flowEyebrow: "Flujo",
    flowTitle: "Del ruido contractual a una pista que sí se entiende",
    flowBody:
      "La experiencia está pensada para leer rápido: mapa, casos para empezar, explicación y verificación. No para perderse en tablas interminables.",
    flowCards: [
      ["ML", "Detectar", "ContratoLimpio sube primero los contratos que más rompen el comportamiento habitual."],
      ["SH", "Explicar", "Cada caso muestra qué factores empujaron el puntaje y qué parte del patrón se quebró."],
      ["SC", "Verificar", "Todo termina en SECOP II. La plataforma acompaña la lectura; no reemplaza la evidencia."],
    ],
    platformEyebrow: "Plataforma",
    platformTitle: "Tres fases, una sola arquitectura cívica",
    platformBody:
      "Fase 1 ya está viva. Las siguientes fases conectan promesas, dinero, redes y contratistas para convertir VeedurIA en una superficie completa de escrutinio público.",
    phases: [
      ["Activa", "ContratoLimpio", "Semáforo de riesgo sobre SECOP II con mapa, casos guiados, factores explicables y vínculo oficial."],
      ["Activa", "VotóMeter", "Votaciones nominales frente a perfil programático, con gaceta, coherencia y trazabilidad."],
      ["En diseño", "SigueElDinero", "Redes entre donantes, contratistas, funcionarios y sanciones para detectar patrones de captura."],
    ],
    ctaTitle: "Empieza por lo que hoy ya se puede auditar",
    ctaBody:
      "La experiencia principal ya corre dentro de Next.js. ContratoLimpio y VotóMeter comparten shell, diseño, navegación y capa de API para crecer como un solo producto.",
    ctaButton: "Abrir ContratoLimpio",
    footer: "VeedurIA · plataforma cívica bilingüe para leer contratación pública con evidencia y contexto",
    languageLabel: "Idioma",
    statVisualCoverage: "Cobertura visible",
    statVisualSignals: "Capas leídas",
    statVisualThreshold: "Umbrales de lectura",
    statVisualRoadmap: "Ruta del producto",
  },
  en: {
    navModel: "Model",
    navFlow: "How it works",
    navPlatform: "Platform",
    navPhase: "Enter the platform",
    heroEyebrow: "SECOP II · Promises · Networks · Civic AI for public scrutiny",
    heroTitleA: "Contracts, promises,",
    heroTitleB: "and networks",
    heroTitleC: "in one reading layer",
    heroBody:
      "VeedurIA now runs as one web product. ContratoLimpio detects atypical SECOP II signals, VotóMeter contrasts nominal votes against visible programmatic profiles, and SigueElDinero prepares the network layer to follow the full trail.",
    heroPrimary: "Open ContratoLimpio",
    heroSecondary: "Open VotóMeter",
    heroProtocolA: "ContratoLimpio brings forward what breaks the contract pattern.",
    heroProtocolB: "VotóMeter contrasts nominal vote, gazette, and programmatic coherence.",
    heroProtocolC: "SigueElDinero will add networks, flows, and political concentration.",
    heroDataLabel: "Visible data",
    heroPlay: "Platform surface",
    heroPlayBody:
      "Touch a department to shift territorial focus and see how the main reading, active routes, and available data layers respond.",
    heroMapCaption: "Touch the map to change the platform's territorial focus.",
    heroLegendFocus: "focus",
    heroLegendModel: "model",
    heroLegendAlert: "alert",
    heroCardSourceLabel: "source",
    heroCardSourceTitle: "ContratoLimpio",
    heroCardSourceBody: "Official contracts, open filters, and a direct path back to the public file.",
    heroCardModelLabel: "model",
    heroCardModelTitle: "VotóMeter",
    heroCardModelBody: "Nominal vote, programme, and gazette now sit in one reading flow for journalists, NGOs, and citizens.",
    heroCardReviewLabel: "review",
    heroCardReviewTitle: "SigueElDinero",
    heroCardReviewBody: "The third phase will connect donors, contractors, and officials inside the same web shell.",
    heroGraphLabel: "signal traffic",
    stats: [
      ["2.8M", "contracts processed", "Enough historical base for the model to avoid relying on isolated hunches."],
      ["25", "variables per contract", "Value, timing, competition, provider, electoral timing, and concentration."],
      ["5%", "priority band", "The most unusual slice is reviewed first, not treated as a verdict."],
      ["3", "active or rolling phases", "ContratoLimpio and VotóMeter already live on web; SigueElDinero is the next layer."],
    ],
    modelEyebrow: "Model",
    modelTitle: "Explainable AI built for scrutiny, not guesswork",
    modelBody:
      "The platform does not replace human judgment. It orders the contract universe, shows why a case rises in priority, and forces the reader back to the official record.",
    modelCards: [
      ["IF", "Isolation Forest", "Learns what a typical contract looks like and finds deviations without relying on labeled cases."],
      ["25", "Readable variables", "The model uses explainable signals: amount, bidders, modality, timing, and concentration."],
      ["0-100", "Interpretable score", "A high number means the contract looks unusual against the observed pattern. It does not mean guilt."],
      ["REV", "Human review", "AI prioritizes. Journalists, citizens, and watchdogs review context and documentation."],
    ],
    flowEyebrow: "Flow",
    flowTitle: "From raw procurement noise to a lead you can actually read",
    flowBody:
      "The experience is built for fast reading: map, lead cases, explanation, and verification. Not for getting lost inside endless tables.",
    flowCards: [
      ["ML", "Detect", "ContratoLimpio pushes the strongest deviations from normal behavior to the top first."],
      ["SH", "Explain", "Each case shows which factors raised the score and what part of the pattern broke."],
      ["SC", "Verify", "Everything ends in SECOP II. The platform supports the reading; it does not replace evidence."],
    ],
    platformEyebrow: "Platform",
    platformTitle: "Three phases, one civic architecture",
    platformBody:
      "Phase 1 is already live. The next phases connect promises, money, networks, and contractors so VeedurIA becomes a complete accountability surface.",
    phases: [
      ["Active", "ContratoLimpio", "Risk signal over SECOP II with map, guided cases, explainable factors, and the official source link."],
      ["Active", "VotóMeter", "Nominal votes against programmatic profiles, with gazettes, coherence, and traceability."],
      ["In design", "SigueElDinero", "Networks across donors, contractors, public officials, and sanctions to spot capture patterns."],
    ],
    ctaTitle: "Start with what can already be audited today",
    ctaBody:
      "The main experience now runs in Next.js. ContratoLimpio and VotóMeter share shell, design, navigation, and API so VeedurIA can grow as one product.",
    ctaButton: "Open ContratoLimpio",
    footer: "VeedurIA · bilingual civic platform for reading public procurement with evidence and context",
    languageLabel: "Language",
    statVisualCoverage: "Visible coverage",
    statVisualSignals: "Readable layers",
    statVisualThreshold: "Reading thresholds",
    statVisualRoadmap: "Product path",
  },
} as const;

export const contractsCopy = {
  es: {
    navPhase1: "ContratoLimpio",
    navPhase2: "VotóMeter",
    navPhase3: "SigueElDinero",
    stateActive: "Activa",
    stateSoon: "En diseño",
    pageEyebrow: "Fase 1 · SECOP II",
    pageTitle: "Sigue la pista del contrato, no la tabla",
    pageBody:
      "ContratoLimpio ordena primero lo que conviene revisar: territorio, caso principal, factores y verificación. La tabla queda como evidencia de apoyo, no como punto de partida.",
    simpleFilters: "Definir corte",
    applyFilters: "Aplicar corte",
    searchPlaceholder: "Buscar entidad o proveedor",
    searchLabel: "Búsqueda",
    filterDepartment: "Departamento",
    filterRisk: "Riesgo",
    filterModality: "Modalidad",
    filterDateFrom: "Desde",
    filterDateTo: "Hasta",
    filterAll: "Todo",
    riskAll: "Todo",
    riskHigh: "Alto",
    riskMedium: "Medio",
    riskLow: "Bajo",
    togglePreview: "Vista rápida",
    toggleFull: "Historial completo",
    metricSlice: "Corte activo",
    metricAlerts: "Alertas altas",
    metricTerritory: "Territorio líder",
    metricModel: "Dato más reciente",
    dashboardTitle: "Qué cambia en este corte",
    dashboardBody: "Cada cifra responde al territorio, la búsqueda y el nivel de riesgo que tengas activos.",
    previewNote:
      "La vista rápida carga primero 50 mil contratos para mantener la interacción fluida. Si activas fechas o historial completo, el tablero usa todo el universo puntuado disponible.",
    previewFull: "Historial completo activo",
    riskMeterTitle: "Cómo leer el medidor de riesgo",
    riskMeterBody:
      "El score ordena qué tan inusual luce un contrato frente al patrón histórico observado. Sirve para priorizar revisión, no para afirmar irregularidad.",
    riskMeterLow: "0–39 · comportamiento cercano al patrón esperado",
    riskMeterMedium: "40–69 · ruptura parcial del patrón, conviene revisar contexto",
    riskMeterHigh: "70–100 · señal fuerte de anomalía, revisar primero",
    guideTitle: "Cómo leer este corte",
    guideBody: "Territorio, señal, explicación y fuente oficial, en ese orden.",
    guideStepTerritory: "Define territorio, riesgo o búsqueda.",
    guideStepSignal: "Abre el caso líder para entender la señal.",
    guideStepVerify: "Verifica en SECOP II antes de concluir.",
    modelHonesty: "El modelo prioriza contratos inusuales. No prueba irregularidad.",
    kpiContracts: "Contratos en corte",
    kpiPriorityValue: "Valor priorizado",
    kpiSelectedCase: "Caso enfocado",
    kpiSelectedSignal: "Señal principal",
    currentSlice: "Lectura actual",
    currentSliceDefault: "Todo Colombia",
    mapTitle: "Dónde se concentra la señal",
    mapBody: "El mapa te deja recortar la lectura por territorio y sacar del camino lo que no importa ahora.",
    mapLegendLow: "menor señal",
    mapLegendHigh: "mayor señal",
    mapFocusTitle: "Territorio dominante del corte",
    mapFocusBody: "Esta base resume dónde se concentra hoy la lectura y te deja saltar entre cortes rápidos sin perder contexto.",
    mapQuickCuts: "Cortes rápidos",
    mapFreshness: "Fecha más reciente",
    mapFreshnessSource: "Fuente SECOP hoy",
    freshnessTitle: "Frescura del dato",
    freshnessScored: "Capa IA visible",
    freshnessSource: "SECOP oficial",
    freshnessGap: "brecha de actualización",
    freshnessGapNone: "sin brecha visible",
    liveFeedTitle: "Contratos más recientes en SECOP",
    liveFeedBody: "Esta lista viene de la fuente oficial hoy. Si supera la capa IA visible, el scoring local todavía está desfasado.",
    liveFeedEmpty: "No se pudo cargar una muestra en vivo desde SECOP.",
    liveFeedRows: "filas en la fuente",
    casesTitle: "Contrato para revisar primero",
    casesBody: "Aquí empieza la lectura guiada del corte: el caso más útil para entender señal, valor y contexto.",
    casesGuide: "Abre un caso para ver por qué subió y cómo verificarlo.",
    caseSynopsis: "Lectura rápida del caso",
    caseContext: "Contexto del caso",
    caseFactorsPanel: "Qué empuja este caso",
    caseQueueTitle: "Casos para contrastar",
    focusTitle: "Lectura principal del corte",
    focusBody: "Este es el contrato que mejor combina señal, monto y recencia dentro del corte activo.",
    otherCasesTitle: "Casos para contrastar",
    otherCasesBody: "Úsalos para comprobar si el patrón se repite antes de bajar al explorador completo.",
    noCases: "No hay contratos para este corte.",
    whyHere: "Por qué está aquí",
    selectedCase: "Caso seleccionado",
    factorsTitle: "Factores que elevaron el puntaje",
    factorsHint: "Las barras más largas representan señales que más empujaron el caso fuera del patrón esperado.",
    detailEntity: "Entidad",
    detailProvider: "Proveedor",
    detailModality: "Modalidad",
    detailValue: "Valor",
    methodology: "Metodología",
    methodologyBody:
      "Isolation Forest prioriza contratos estadísticamente inusuales. SHAP traduce esa anomalía en factores legibles. El resultado sirve para orientar revisión, no para concluir ilegalidad.",
    methodologyWhyModel:
      "Usamos Isolation Forest porque no existe una etiqueta confiable y masiva de corrupción para entrenar un clasificador supervisado. Para auditoría preventiva con datos abiertos, es un punto de partida razonable y explicable.",
    summaryEntities: "Entidades que conviene revisar primero",
    summaryModalities: "Modalidades con riesgo medio más alto",
    summaryContracts: "contratos",
    summaryMax: "máx.",
    summaryMean: "prom.",
    analysisTitle: "Evidencia y contexto",
    analysisBody: "Mueve esta zona entre resúmenes, explorador y metodología sin romper la lectura principal.",
    analysisEntities: "Entidades",
    analysisModalities: "Modalidades",
    analysisExplorer: "Explorador",
    analysisMethodology: "Modelo",
    tableTitle: "Explorador del corte",
    tableBody: "Aquí contrastas, ordenas y validas todo lo que el mapa y el caso principal ya te mostraron.",
    tableNote: "Aquí ves el universo completo del corte seleccionado. Arriba está la lectura guiada; abajo, la evidencia completa.",
    tableScore: "Puntaje",
    tableEntity: "Entidad",
    tableDepartment: "Departamento",
    tableModality: "Modalidad",
    tableValue: "Valor",
    tableSource: "Fuente",
    tableValueRelative: "Peso en el corte",
    verify: "Ver en SECOP II",
    ethicalNote: "Alerta preventiva. No es una acusación automática.",
    rows: "filas",
    loading: "Cargando",
    previous: "Anterior",
    next: "Siguiente",
  },
  en: {
    navPhase1: "ContratoLimpio",
    navPhase2: "VotóMeter",
    navPhase3: "SigueElDinero",
    stateActive: "Active",
    stateSoon: "In design",
    pageEyebrow: "Phase 1 · SECOP II",
    pageTitle: "Follow the contract trail, not the table",
    pageBody:
      "ContratoLimpio brings forward what deserves review first: territory, lead case, factors, and verification. The table stays as supporting evidence, not as the starting point.",
    simpleFilters: "Define slice",
    applyFilters: "Apply slice",
    searchPlaceholder: "Search entity or provider",
    searchLabel: "Search",
    filterDepartment: "Department",
    filterRisk: "Risk",
    filterModality: "Modality",
    filterDateFrom: "From",
    filterDateTo: "To",
    filterAll: "All",
    riskAll: "All",
    riskHigh: "High",
    riskMedium: "Medium",
    riskLow: "Low",
    togglePreview: "Quick view",
    toggleFull: "Full history",
    metricSlice: "Active slice",
    metricAlerts: "High alerts",
    metricTerritory: "Leading territory",
    metricModel: "Latest data point",
    dashboardTitle: "What changes in this slice",
    dashboardBody: "Each number responds to the territory, search, and risk level currently active.",
    previewNote:
      "Quick view loads the latest 50k contracts first to keep the experience fast. If you activate dates or full history, the dashboard switches to the full scored universe available.",
    previewFull: "Full history active",
    riskMeterTitle: "How to read the risk meter",
    riskMeterBody:
      "The score orders how unusual a contract looks against the observed historical pattern. It is built for review priority, not for declaring wrongdoing.",
    riskMeterLow: "0–39 · still close to the expected pattern",
    riskMeterMedium: "40–69 · partial break from the pattern, review context",
    riskMeterHigh: "70–100 · strong anomaly signal, review first",
    guideTitle: "How to read this slice",
    guideBody: "Territory, signal, explanation, and official source, in that order.",
    guideStepTerritory: "Define territory, risk, or search.",
    guideStepSignal: "Open the lead case to understand the signal.",
    guideStepVerify: "Verify in SECOP II before concluding.",
    modelHonesty: "The model prioritizes unusual contracts. It does not prove wrongdoing.",
    kpiContracts: "Contracts in slice",
    kpiPriorityValue: "Prioritized value",
    kpiSelectedCase: "Focused case",
    kpiSelectedSignal: "Primary signal",
    currentSlice: "Current reading",
    currentSliceDefault: "All Colombia",
    mapTitle: "Where the signal concentrates",
    mapBody: "The map lets you narrow the reading by territory and remove what does not matter right now.",
    mapLegendLow: "lower signal",
    mapLegendHigh: "higher signal",
    mapFocusTitle: "Leading territory in this slice",
    mapFocusBody: "This base shows where the reading is concentrating right now and lets you jump across quick slices without losing context.",
    mapQuickCuts: "Quick slices",
    mapFreshness: "Latest date",
    mapFreshnessSource: "SECOP source today",
    freshnessTitle: "Data freshness",
    freshnessScored: "Visible AI layer",
    freshnessSource: "Official SECOP",
    freshnessGap: "update gap",
    freshnessGapNone: "no visible gap",
    liveFeedTitle: "Latest contracts in SECOP",
    liveFeedBody: "This list comes from the official source today. If it is newer than the visible AI layer, local scoring is still behind.",
    liveFeedEmpty: "A live SECOP sample could not be loaded.",
    liveFeedRows: "rows at source",
    casesTitle: "Contract to review first",
    casesBody: "This is where the guided reading starts: the most useful case for understanding signal, value, and context.",
    casesGuide: "Open a case to see why it rose and how to verify it.",
    caseSynopsis: "Quick case read",
    caseContext: "Case context",
    caseFactorsPanel: "What pushes this case",
    caseQueueTitle: "Cases to compare",
    focusTitle: "Main reading for this slice",
    focusBody: "This is the contract that best combines signal, value, and recency in the active slice.",
    otherCasesTitle: "Cases to compare",
    otherCasesBody: "Use them to check whether the pattern repeats before moving into the full explorer.",
    noCases: "No contracts in this slice.",
    whyHere: "Why it is here",
    selectedCase: "Selected case",
    factorsTitle: "Factors that raised the score",
    factorsHint: "Longer bars represent signals that pushed the case furthest outside the expected pattern.",
    detailEntity: "Entity",
    detailProvider: "Provider",
    detailModality: "Modality",
    detailValue: "Value",
    methodology: "Methodology",
    methodologyBody:
      "Isolation Forest prioritizes statistically unusual contracts. SHAP turns that anomaly into readable factors. The result guides review; it does not establish wrongdoing.",
    methodologyWhyModel:
      "We use Isolation Forest because there is no trustworthy large-scale corruption label to train a supervised classifier. For preventive auditing with open data, it is a reasonable and explainable starting point.",
    summaryEntities: "Entities worth checking first",
    summaryModalities: "Modalities with the highest mean risk",
    summaryContracts: "contracts",
    summaryMax: "max",
    summaryMean: "mean",
    analysisTitle: "Evidence and context",
    analysisBody: "Move this area across summaries, explorer, and methodology without breaking the main reading flow.",
    analysisEntities: "Entities",
    analysisModalities: "Modalities",
    analysisExplorer: "Explorer",
    analysisMethodology: "Model",
    tableTitle: "Slice explorer",
    tableBody: "Use it to contrast, sort, and validate everything the map and the lead case already surfaced.",
    tableNote: "This is the full universe for the selected slice. The guided reading sits above; the complete evidence lives here.",
    tableScore: "Score",
    tableEntity: "Entity",
    tableDepartment: "Department",
    tableModality: "Modality",
    tableValue: "Value",
    tableSource: "Source",
    tableValueRelative: "Weight in slice",
    verify: "Open in SECOP II",
    ethicalNote: "Preventive alert. This is not an automatic accusation.",
    rows: "rows",
    loading: "Loading",
    previous: "Previous",
    next: "Next",
  },
} as const;

export const promisesCopy = {
  es: {
    navPhase1: "ContratoLimpio",
    navPhase2: "VotóMeter",
    navPhase3: "SigueElDinero",
    pageEyebrow: "Fase 2 · Promesas y acción política",
    pageTitle: "Promesas públicas frente a evidencia verificable",
    pageBody:
      "VotóMeter contrasta votaciones nominales con el perfil programático disponible. No sentencia legisladores: ordena coherencia, abre gacetas y deja explícito cuándo la cobertura sigue siendo parcial.",
    activePilot: "Cobertura piloto",
    activeLive: "Cobertura activa",
    activeRealNames: "Perfiles reales",
    searchLabel: "Búsqueda",
    searchPlaceholder: "Buscar promesa, evidencia o partido",
    filterPolitician: "Político",
    filterDomain: "Dominio",
    filterStatus: "Estado",
    filterYear: "Periodo",
    applyFilters: "Actualizar lectura",
    all: "Todo",
    kpiPoliticians: "Perfiles visibles",
    kpiPromises: "Promesas leídas",
    kpiCoherence: "Coherencia activa",
    kpiDomains: "Dominios activos",
    scorecardEyebrow: "Scorecard",
    scorecardTitle: "Lectura del perfil",
    scorecardBody: "El puntaje resume cuánta acción relevante aparece para este perfil dentro de la cobertura disponible.",
    scoreOverall: "Coherencia global",
    scoreFulfilled: "Con acción registrada",
    scoreMonitoring: "En seguimiento",
    scoreNoAction: "Sin evidencia disponible",
    domainBreakdown: "Lectura por dominio",
    cardsEyebrow: "Compromisos",
    cardsTitle: "Promesas para verificar",
    cardsBody: "Cada tarjeta junta compromiso, evidencia enlazada y la distancia semantica que encontro el modelo.",
    cardsEmpty: "No hay promesas para este corte.",
    confidence: "Confianza",
    similarity: "Similitud NLP",
    extraction: "Extracción",
    promiseSource: "Fuente del compromiso",
    actionSource: "Fuente de la acción",
    evidence: "Evidencia enlazada",
    noEvidence: "Sin evidencia util en esta corrida.",
    methodologyEyebrow: "Método",
    methodologyTitle: "Cómo leer la coherencia",
    methodologyBody:
      "La similitud compara lenguaje de promesas con lenguaje de acciones. Sirve para priorizar lectura y contraste documental, no para declarar cumplimiento automático.",
    methodologyRuleA: "0.72 o más: acción registrada cercana al compromiso.",
    methodologyRuleB: "0.45 a 0.71: hay movimiento parcial y conviene seguir el rastro.",
    methodologyRuleC: "Por debajo de 0.45: no aparece evidencia suficiente en la cobertura actual.",
    methodologyNote:
      "Si la cobertura aún es piloto, la ausencia de evidencia puede significar vacíos de datos y no necesariamente ausencia de acción.",
    highlightsPolitician: "Perfil en foco",
    highlightsDomain: "Dominio dominante",
    highlightsStatus: "Estado dominante",
    verifyPromise: "Abrir fuente",
    verifyAction: "Abrir evidencia",
    footerPilot:
      "VotóMeter ya corre dentro del producto web. La cobertura sigue siendo piloto, pero los nombres visibles ya corresponden a perfiles rastreables del ciclo 2026.",
  },
  en: {
    navPhase1: "ContratoLimpio",
    navPhase2: "VotóMeter",
    navPhase3: "SigueElDinero",
    pageEyebrow: "Phase 2 · Promises and political action",
    pageTitle: "Public promises against verifiable evidence",
    pageBody:
      "VotóMeter contrasts nominal votes with the available programmatic profile. It does not judge legislators: it orders coherence, opens gazettes, and makes partial coverage explicit.",
    activePilot: "Pilot coverage",
    activeLive: "Live coverage",
    activeRealNames: "Real profiles",
    searchLabel: "Search",
    searchPlaceholder: "Search promise, evidence, or party",
    filterPolitician: "Politician",
    filterDomain: "Domain",
    filterStatus: "Status",
    filterYear: "Period",
    applyFilters: "Update reading",
    all: "All",
    kpiPoliticians: "Profiles visible",
    kpiPromises: "Promises read",
    kpiCoherence: "Active coherence",
    kpiDomains: "Active domains",
    scorecardEyebrow: "Scorecard",
    scorecardTitle: "Profile reading",
    scorecardBody: "The score summarizes how much relevant action appears for this profile inside the available coverage.",
    scoreOverall: "Overall coherence",
    scoreFulfilled: "With registered action",
    scoreMonitoring: "Under monitoring",
    scoreNoAction: "No evidence available",
    domainBreakdown: "Domain breakdown",
    cardsEyebrow: "Commitments",
    cardsTitle: "Promises to verify",
    cardsBody: "Each card brings together a commitment, linked evidence, and the semantic distance found by the model.",
    cardsEmpty: "No promises in this slice.",
    confidence: "Confidence",
    similarity: "NLP similarity",
    extraction: "Extraction",
    promiseSource: "Promise source",
    actionSource: "Action source",
    evidence: "Linked evidence",
    noEvidence: "No useful evidence in this run.",
    methodologyEyebrow: "Method",
    methodologyTitle: "How to read coherence",
    methodologyBody:
      "Similarity compares promise language with action language. It is built to prioritize reading and document contrast, not to declare automatic fulfillment.",
    methodologyRuleA: "0.72 or above: registered action close to the commitment.",
    methodologyRuleB: "0.45 to 0.71: partial movement is visible and deserves follow-up.",
    methodologyRuleC: "Below 0.45: there is not enough evidence in the current coverage.",
    methodologyNote:
      "If coverage is still pilot-only, missing evidence may reflect data gaps rather than absence of action.",
    highlightsPolitician: "Profile in focus",
    highlightsDomain: "Dominant domain",
    highlightsStatus: "Dominant status",
    verifyPromise: "Open source",
    verifyAction: "Open evidence",
    footerPilot:
      "VotóMeter already runs in the web layer. Coverage is still pilot, but visible names already match traceable 2026 profiles.",
  },
} as const;

// ─── SigueElDinero copy ────────────────────────────────────────────────────────

export const sigueDineroCopy = {
  es: {
    eyebrow: "Fase 3 · Redes de contratación",
    title: "SigueElDinero",
    subtitle:
      "Explora quién contrata con quién, cómo se concentra el gasto público y qué relaciones se repiten.",
    ethicalNote:
      "Muestra relaciones observables en datos públicos. No prueba irregularidad.",
    searchPlaceholder: "Busca entidad, proveedor o palabra clave…",
    searchButton: "Explorar red",
    howToRead: "Cómo leer este mapa",
    tabNetwork: "Red",
    tabConcentration: "Concentración",
    tabEvidence: "Evidencia",
    filterTitle: "Filtros",
    filterToggle: "Filtros avanzados",
    filterDepartment: "Departamento",
    filterModality: "Modalidad",
    filterDateFrom: "Desde",
    filterDateTo: "Hasta",
    filterConfidence: "Confianza mínima",
    filterConfidenceAll: "Todas",
    filterConfidenceVerified: "Verificadas",
    filterConfidenceHigh: "Alta confianza",
    filterApply: "Aplicar",
    filterReset: "Limpiar",
    panelEmpty: "Haz clic en un nodo para ver su detalle.",
    panelExpand: "Expandir conexiones",
    panelExpanding: "Expandiendo…",
    panelType_entity: "Entidad pública",
    panelType_provider: "Proveedor",
    panelType_cluster: "Grupo agrupado",
    panelTotalValue: "Total contratado",
    panelContracts: "Contratos",
    panelConnections: "Conexiones",
    panelConcentration: "Concentración (HHI)",
    panelTopConnections: "Principales relaciones",
    panelEvidence: "Ver contratos",
    panelDateRange: "Período",
    panelModalities: "Modalidades",
    panelNoConnections: "Sin relaciones detectadas",
    disclaimer:
      "Esta es una alerta preventiva generada automáticamente. No constituye prueba de irregularidad. Consulte los documentos del proceso antes de concluir.",
    loadingGraph: "Construyendo red…",
    loadingRelations: "Calculando relaciones…",
    loadingConfidence: "Verificando confianza…",
    noResults: "Sin resultados para esa búsqueda.",
    noResultsHint: "Intenta con el nombre completo de la entidad o un NIT.",
    hintZoom: "Rueda para zoom · Arrastrar para mover · Clic en nodo para detalles",
    hintEdgeClick: "Clic en una línea para ver la evidencia de esa relación",
    errorGeneric: "No se pudo cargar la red. Cargando datos de referencia.",
    errorRetry: "Reintentar",
    errorFallback: "Si el problema persiste, la red cargará con datos de referencia.",
    legendTitle: "Leyenda",
    legendNodeSize: "Tamaño del nodo = volumen contratado",
    legendEdgeWidth: "Grosor de línea = número de contratos",
    legendConfidenceHigh: "Verde = alta confianza (≥80)",
    legendConfidenceMed: "Amarillo = confianza media (60–79)",
    legendConfidenceLow: "Rojo = relación inferida (<60)",
    evidenceTitle: "Evidencia de la relación",
    evidenceSource: "Fuente oficial",
    evidenceDocument: "Documento",
    evidenceDate: "Fecha",
    evidenceAlgorithm: "Método de verificación",
    evidenceConfidence: "Confianza",
    evidenceViewSource: "Ver en fuente oficial",
    evidenceReportError: "Reportar error en esta relación",
    evidenceReportDescription: "Describe el problema",
    evidenceReportSend: "Enviar reporte",
    evidenceReportSent: "Reporte recibido. Gracias.",
    concentrationTitle: "Concentración de gasto",
    concentrationSubtitle: "Entidades con mayor concentración en pocos proveedores",
    concentrationHhiLabel: "Índice HHI",
    concentrationTopProviders: "Top proveedores por entidad",
    concentrationShare: "Participación",
    resetView: "Restablecer vista",
    zoomIn: "Acercar",
    zoomOut: "Alejar",
    totalNodes: "nodos",
    totalEdges: "relaciones",
    nodeZeroConnections: "Sin relaciones detectadas",
    clusterLabel: "proveedores agrupados",
  },
  en: {
    eyebrow: "Phase 3 · Contracting networks",
    title: "SigueElDinero",
    subtitle:
      "Explore who contracts with whom, how public spending concentrates, and which relationships repeat.",
    ethicalNote:
      "Shows observable relationships in public data. Does not prove wrongdoing.",
    searchPlaceholder: "Search entity, provider, or keyword…",
    searchButton: "Explore network",
    howToRead: "How to read this map",
    tabNetwork: "Network",
    tabConcentration: "Concentration",
    tabEvidence: "Evidence",
    filterTitle: "Filters",
    filterToggle: "Advanced filters",
    filterDepartment: "Department",
    filterModality: "Modality",
    filterDateFrom: "From",
    filterDateTo: "To",
    filterConfidence: "Minimum confidence",
    filterConfidenceAll: "All",
    filterConfidenceVerified: "Verified",
    filterConfidenceHigh: "High confidence",
    filterApply: "Apply",
    filterReset: "Clear",
    panelEmpty: "Click a node to see its details.",
    panelExpand: "Expand connections",
    panelExpanding: "Expanding…",
    panelType_entity: "Public entity",
    panelType_provider: "Provider",
    panelType_cluster: "Clustered group",
    panelTotalValue: "Total contracted",
    panelContracts: "Contracts",
    panelConnections: "Connections",
    panelConcentration: "Concentration (HHI)",
    panelTopConnections: "Top relationships",
    panelEvidence: "View contracts",
    panelDateRange: "Period",
    panelModalities: "Modalities",
    panelNoConnections: "No relationships detected",
    disclaimer:
      "This is an automatically generated preventive alert. It does not constitute evidence of wrongdoing. Review source documents before drawing conclusions.",
    loadingGraph: "Building network…",
    loadingRelations: "Calculating relationships…",
    loadingConfidence: "Verifying confidence…",
    noResults: "No results for that search.",
    noResultsHint: "Try the full entity name or a NIT number.",
    hintZoom: "Scroll to zoom · Drag to pan · Click node for details",
    hintEdgeClick: "Click a line to view evidence for that relationship",
    errorGeneric: "Could not load the network. Loading reference data.",
    errorRetry: "Retry",
    errorFallback: "If the problem persists, the network will load with reference data.",
    legendTitle: "Legend",
    legendNodeSize: "Node size = contract volume",
    legendEdgeWidth: "Line width = number of contracts",
    legendConfidenceHigh: "Green = high confidence (≥80)",
    legendConfidenceMed: "Yellow = medium confidence (60–79)",
    legendConfidenceLow: "Red = inferred relation (<60)",
    evidenceTitle: "Relationship evidence",
    evidenceSource: "Official source",
    evidenceDocument: "Document",
    evidenceDate: "Date",
    evidenceAlgorithm: "Verification method",
    evidenceConfidence: "Confidence",
    evidenceViewSource: "View in official source",
    evidenceReportError: "Report error in this relationship",
    evidenceReportDescription: "Describe the issue",
    evidenceReportSend: "Submit report",
    evidenceReportSent: "Report received. Thank you.",
    concentrationTitle: "Spending concentration",
    concentrationSubtitle: "Entities with highest concentration in few providers",
    concentrationHhiLabel: "HHI Index",
    concentrationTopProviders: "Top providers per entity",
    concentrationShare: "Share",
    resetView: "Reset view",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    totalNodes: "nodes",
    totalEdges: "relationships",
    nodeZeroConnections: "No relationships detected",
    clusterLabel: "grouped providers",
  },
} as const;

export type SigueDineroCopyLang = (typeof sigueDineroCopy)["es"];
